/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generic_courier_company_the_software;

import java.awt.Color;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Lenovo
 */
public class NewPackageForm extends javax.swing.JFrame implements CourierConstants{
    String message;
    /**
     * Creates new form NewPackageForm
     */
    public NewPackageForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        datelabel = new javax.swing.JLabel();
        yeartext = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        monthtext = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        daytext = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hourtext = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        minutetext = new javax.swing.JTextField();
        weightlabel = new javax.swing.JLabel();
        weighttext = new javax.swing.JTextField();
        volumetext = new javax.swing.JTextField();
        volumelabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        courierlabel = new javax.swing.JLabel();
        couriertext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addresstext = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        descriptionlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        submitbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Package Form");

        datelabel.setText("Date (YYYY / MM / DD) & Time (HHMM)");

        yeartext.setText("2017");

        jLabel7.setText("/");

        monthtext.setText("01");
        monthtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthtextActionPerformed(evt);
            }
        });

        jLabel8.setText("/");

        daytext.setText("01");
        daytext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daytextActionPerformed(evt);
            }
        });

        jLabel9.setText("; ");

        hourtext.setText("24");

        jLabel10.setText(":");

        minutetext.setText("00");

        weightlabel.setText("Weight:");

        weighttext.setPreferredSize(new java.awt.Dimension(50, 22));

        volumetext.setPreferredSize(new java.awt.Dimension(50, 22));
        volumetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumetextActionPerformed(evt);
            }
        });

        volumelabel.setBackground(new java.awt.Color(204, 204, 204));
        volumelabel.setText("Volume: ");

        jLabel13.setText("kg");

        jLabel14.setText("cu. cm");

        courierlabel.setText("Courier ID:");

        couriertext.setToolTipText("");
        couriertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couriertextActionPerformed(evt);
            }
        });

        jLabel2.setText("Address:");

        addresstext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresstextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(weightlabel)
                        .addGap(18, 18, 18)
                        .addComponent(weighttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(89, 89, 89)
                        .addComponent(courierlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(couriertext))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(addresstext))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(datelabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(yeartext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(monthtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(daytext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(hourtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(minutetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(volumelabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(volumetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel14)))
                            .addGap(0, 76, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datelabel)
                    .addComponent(yeartext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(monthtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(daytext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(hourtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(minutetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightlabel)
                    .addComponent(weighttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(courierlabel)
                    .addComponent(couriertext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volumelabel)
                    .addComponent(volumetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        descriptionlabel.setText("Description (500 char):");

        description.setColumns(20);
        description.setLineWrap(true);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(descriptionlabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        cancelbutton.setText("Cancel");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(submitbutton)
                .addGap(18, 18, 18)
                .addComponent(cancelbutton)
                .addGap(63, 63, 63))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitbutton)
                    .addComponent(cancelbutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NEW PACKAGE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel1))))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void monthtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthtextActionPerformed

    private void daytextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daytextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daytextActionPerformed

    private void volumetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volumetextActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        if(validinputs()){
            try{
                String datedeposit = yeartext.getText()+monthtext.getText()+daytext.getText();
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection(database_url, "root", "");
                PreparedStatement track = conn.prepareStatement("SELECT package_ID FROM package_inventory WHERE deposit_date = " + datedeposit);
                ResultSet rs = track.executeQuery();
                String trackingnum="1";
                long packID=0;
                if(rs.next()){
                    track = conn.prepareStatement("SELECT MAX(package_ID) FROM package_inventory WHERE deposit_date = " + datedeposit);
                    rs = track.executeQuery();
                    rs.next();
                    packID = rs.getLong(1);
                    trackingnum = Long.toHexString(++packID);
                    
                }
                else{
                    trackingnum = Long.toHexString(Long.parseLong(yeartext.getText()+monthtext.getText()+daytext.getText()+"000000")).toUpperCase();
                }
                //System.out.println("ID: " + Long.decode("0x"+trackingnum) + "\nTracking: " + trackingnum);
                PreparedStatement pst = conn.prepareStatement(fullinsert);
                pst.setLong(1, packID);
                pst.setString(2, trackingnum);
                pst.setInt(3, Integer.parseInt(hourtext.getText() + minutetext.getText()));
                pst.setInt(4, Integer.parseInt(datedeposit));
                pst.setDouble(5, Double.parseDouble(weighttext.getText()));
                pst.setDouble(6, Double.parseDouble(volumetext.getText()));
                pst.setString(7, description.getText());
                pst.setString(8, addresstext.getText());
                pst.setString(9, "Processing");
                pst.setInt(10, Integer.parseInt(couriertext.getText()));
                pst.setObject(11, null);
                pst.setObject(12, null);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"New Package Submitted","New Package", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Database Error " + e);
                System.out.println(e);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, message, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void couriertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couriertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_couriertextActionPerformed

    private void addresstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresstextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addresstextActionPerformed

    private boolean validinputs(){
        message = "Invalid Package Details";
        
        boolean valid = true;
        datelabel.setBackground(labeldefaultbg);
        datelabel.setOpaque(false);
        weightlabel.setBackground(labeldefaultbg);
        weightlabel.setOpaque(false);
        volumelabel.setBackground(labeldefaultbg);
        volumelabel.setOpaque(false);
        courierlabel.setBackground(labeldefaultbg);
        courierlabel.setOpaque(false);
        descriptionlabel.setBackground(labeldefaultbg);
        descriptionlabel.setOpaque(false);
        
        if(
                Integer.parseInt(yeartext.getText())<0 ||
                Integer.parseInt(monthtext.getText())<1 ||
                Integer.parseInt(monthtext.getText())>12 ||
                Integer.parseInt(daytext.getText()) < 1 ||
                Integer.parseInt(daytext.getText()) > 31 ){
            datelabel.setOpaque(true);
            datelabel.setBackground(Color.orange);
            valid=false;
        }
        if(couriertext.getText().length()==0){
            courierlabel.setOpaque(true);
            courierlabel.setBackground(Color.orange);
            message += "\nCourier ID field empty";
            valid=false;
        }
        else{
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection(database_url, "root", "");
                Statement stat = conn.createStatement();
                ResultSet rs = stat.executeQuery("Select * from courier_list where employee_ID = " + couriertext.getText());
                if(!rs.next()){
                    courierlabel.setOpaque(true);
                    courierlabel.setBackground(Color.orange);
                    message += "\nEmployee ID not found";
                    valid=false;
                }
            
            }catch(Exception e){
                System.out.println(e);
            }
        }
        if(weighttext.getText().length()==0){
            weightlabel.setOpaque(true);
            weightlabel.setBackground(Color.orange);
            message += "\nWeight field empty";
            valid=false;
        }
        else if(Double.parseDouble(weighttext.getText())<0){
            weightlabel.setOpaque(true);
            weightlabel.setBackground(Color.orange);
            valid=false;
        }
        if(volumetext.getText().length()==0){
            volumelabel.setOpaque(true);
            volumelabel.setBackground(Color.orange);
            message += "\nVolume field empty";
            valid=false;
        }
        else if(Double.parseDouble(volumetext.getText())<0){
            volumelabel.setOpaque(true);
            volumelabel.setBackground(Color.orange);
            valid=false;
        }
        if(description.getText().length()>500){
            descriptionlabel.setOpaque(true);
            descriptionlabel.setBackground(Color.orange);
            message += "\nDescription exceeds character limit";
            valid=false;
        }
        
        return valid;
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPackageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPackageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPackageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPackageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPackageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstext;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JLabel courierlabel;
    private javax.swing.JTextField couriertext;
    private javax.swing.JLabel datelabel;
    private javax.swing.JTextField daytext;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel descriptionlabel;
    private javax.swing.JTextField hourtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField minutetext;
    private javax.swing.JTextField monthtext;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel volumelabel;
    private javax.swing.JTextField volumetext;
    private javax.swing.JLabel weightlabel;
    private javax.swing.JTextField weighttext;
    private javax.swing.JTextField yeartext;
    // End of variables declaration//GEN-END:variables
}
